[project]
name = "b-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pysnmplib>=5.0.24",
    "snmpclitools>=0.7.2",
]
