[project]
name = "b-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "d2l>=0.17.0",
    "numpy>=2.1.3",
    "pandas>=2.2.3",
    "pysnmplib>=5.0.24",
    "snmpclitools>=0.7.2",
    "torch>=2.5.1",
]
